name: Firebase Deploy

on:
  push:
    paths:
      - "functions/**"
      - "src/**"
      - "public/**"
      - "firebase.json"
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install root dependencies
        run: npm install

      - name: Crear .env global compartido
        run: echo "${{ secrets.ENV_CLOUD }}" > .env

      - name: Copiar .env a web
        run: cp .env ./web/.env

      - name: Copiar .env a functions
        run: cp .env ./functions/.env

      - name: Build frontend (Vite)
        run: npm run build

      - name: Set up Service Account credentials
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud.json
        run: firebase deploy --only hosting,functions --project gaid-agent