name: Snyk Scan

on:
  push:
    branches: [master]
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Snyk scan (root)
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_CARLOSDELGADO }}

      - name: Install functions dependencies
        run: |
          cd functions
          npm install

      - name: Snyk scan (functions)
        run: |
          cd functions
          npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_CARLOSDELGADO }}